### ISSUE TITLE
Optional HTTP authentication - Generic hook

### ISSUE THREAD

**Issue by kallisti5** [irccloud/irccat#18]
I know it's currently not supported, but some kind of authentication via HTTP would be useful. (even if it's a static token/password vs http auth)

**Comment by kallisti5** [comment]
It looks like it would be pretty easy to at minimum expect a token via an HTTP header before accepting a broadcast message to an IRC server.

https://github.com/irccloud/irccat/blob/master/httplistener/generic.go#L14

Example:
```
 X-IRCCat-AccessKey: ret24r43tg3wrrgeqger
```

**Comment by russss** [comment]
Yeah, it would be fairly simple to make this optional for the generic HTTP endpoint. The other endpoints are dependent on the webhook sender supporting authentication.

I'd recommend using standard HTTP auth with the standard "bearer token" pattern - i.e. `Authorization: Bearer <key>`.

**Comment by kallisti5** [comment]
Done! That wasn't too hard :-)

kallisti5@eris irccat :) $ echo "Hello world" | curl -H "Authorization: Bearer lol" -d @- http://127.0.0.1:8045/send

kallisti5@eris irccat :) $ echo "Hello world" | curl -H "Authorization: Bearer lo" -d @- http://127.0.0.1:8045/send
Invalid Authorization

**Comment by russss** [comment]
Fixed in 0ed531f.
